// Auto-generated from legacy resume data
// Source: openspec/legacy-code-snippets/resumes.ts
// DO NOT EDIT MANUALLY

import { Resume } from "../types";

export const RESUMES: Resume[] = [
  {
    "repId": "rep1",
    "name": "Marvin Adams",
    "gender": "M",
    "education": "2 years Ohio State University",
    "experience": "4 years in the United States Army",
    "intelligence": 32,
    "myers_briggs": "ISTP",
    "other_info": "Purple Heart recipient",
    "interview": "Marvin carries himself like you would expect from someone fresh out of the Army. Says yes sir and no sir. Had well thought out questions and answers. Had a notebook and planner in which he wrote everything down to keep him organized. Has never worked in sales before, but is confident that he will be good at it.",
    "reference_check": "References in the Army say that Marvin was a bit of a slow learner, but was very diligent at the same. He was very organized at all times, but had a tendency to forget information if he didn’t write it down somewhere. Was sent home from the Army after being shot in the arm."
  },
  {
    "repId": "rep2",
    "name": "Karen Adams-Foster",
    "gender": "F",
    "education": "BSBA, George Washington State University",
    "experience": "13 years selling insurance for Brown & Brown",
    "intelligence": 50,
    "myers_briggs": "ESFP",
    "other_info": "Does freelance work as a glassblower in her spare time",
    "interview": "Karen is an exotic dresser. Interesting, fashion-forward sense of style. Great listener. Always restated the questions we asked her to assure she heard them right. Was sick of having strictly capped commissions at her last job, so is looking to sell somewhere where that will not be a concern.",
    "reference_check": "Co-workers all liked Karen, although she was almost never in the office as she preferred to work on the road. Would get the occasional customer complaint, due to the fact that Karen was so good at talking customers into buying policies they really did not need. However, her bosses all loved her for that."
  },
  {
    "repId": "rep3",
    "name": "Quincey Alberta",
    "gender": "M",
    "education": "Associate Degree Technology - Great Lakes Baptist",
    "experience": "9 years computer sales at Aaron’s",
    "intelligence": 48,
    "myers_briggs": "ENFP",
    "other_info": "Boy Scout troop leader and little league baseball coach",
    "interview": "Quincy is a pleasant man. Has 4 boys at home so he lives a very busy life. Very relaxed person. Was not overly concerned when he did not have answers to some of our questions, and did not ask questions at the end of the interview.",
    "reference_check": "Personal references say what a great man Quincy is. His kids in Boy Scouts and on his Little League Baseball team all look up to him. Spends a lot of time playing sports with his sons. Previous employers also say what a great man Quincy, but did say he would take a lot of time off work in order to be there for his family."
  },
  {
    "repId": "rep4",
    "name": "Henrietta Appleby",
    "gender": "F",
    "education": "BS Liberal Studies, University of West Virginia",
    "experience": "6 years floor salesperson at Staples",
    "intelligence": 42,
    "myers_briggs": "ISTJ",
    "other_info": "Devoted mother of 6 children",
    "interview": "Henrietta was very well-prepared for the interview. Took copious notes, and asked terrific questions. Despite her 6 years of experience on the floor of Staples, Henrietta was not all that familiar with the sales process.",
    "reference_check": "Henrietta received positive references from all her former employers. As a mother of 6, there were times Henrietta had to take off work at the last minute, but her work ethic was always second to none."
  },
  {
    "repId": "rep5",
    "name": "Tyler Barnes",
    "gender": "M",
    "education": "BS, Computer Sciences, University of Georgia",
    "experience": "7 years at Radio Shack, 4 years at an Apple outlet store",
    "intelligence": 56,
    "myers_briggs": "ESTP",
    "other_info": "Bow hunter of small game, general outdoorsmen",
    "interview": "A friendly southern gentleman. Wore a nice tie that matched his snakeskin dress shoes from snakes he hunted himself. Tyler is tired of dealing with electronics. Believes they cause too many problems, and would like to sell something that doesn’t end up causing people headaches.",
    "reference_check": "Positive reviews came in from all of Tyler’s previous employers. Occasionally, on bad days, Tyler would receive complaints from customers because he would try to get into political conversations with them, but he never caused that big of a scene."
  },
  {
    "repId": "rep6",
    "name": "Bartholomew Beasters",
    "gender": "M",
    "education": "BA Liberal Studies, Long Beach State University",
    "experience": "Worked in an acupuncture and herbs clinic for past 5 years",
    "intelligence": 32,
    "myers_briggs": "ISFP",
    "other_info": "Attended the American Institute of Alternative Medicine in Columbus, Ohio for a few months, but dropped out.",
    "interview": "Bartholomew has been working in the general field of alternative medicine since he graduated high school in California. Has impressive knowledge of a wide variety of medicinal herbs. Very good listener, came up with creative answers to all of our questions.",
    "reference_check": "Bartholomew’s references all gave him excellent reviews. His last boss stated that, “He is the exact type of guy you would want to get advice from about alternative medicine.” Someone else said that he was a sales natural."
  },
  {
    "repId": "rep7",
    "name": "Thomas Bexton III",
    "gender": "M",
    "education": "BA, Business, Washington University",
    "experience": "1 year as a host at local Italian restaurant",
    "intelligence": 46,
    "myers_briggs": "INTP",
    "other_info": "The Bexton family is known for their oil fortune",
    "interview": "There are many signs that Thomas comes from money.  He came to the interview wearing an Armani suit, and a Rolex watch. Personality wise, however, he did not come across as snobby. Thomas was a quiet, reserved individual who stressed that he hasn’t earned anything in life yet, and knows he has a lot to prove.",
    "reference_check": "Thomas as 6 siblings, and the Bexton family has a reputation for spoiling their children. Thomas went to all the best schools. His parents paid his way through college at Washington University. On the other hand, his current employer at the Italian restaurant was not aware of Thomas’ family’s status until we called for the reference check."
  },
  {
    "repId": "rep8",
    "name": "Rosanna Binghampton",
    "gender": "F",
    "education": "High School Education",
    "experience": "24 year manager at Rob & Bob’s Pizza Buffet",
    "intelligence": 52,
    "myers_briggs": "ISTP",
    "other_info": "Runs a neighborhood daycare with her daughter out of her their own house on weekday mornings",
    "interview": "Rosanna is an intense individual, and quite intimidating to talk to. Not the type of personality you would expect from someone who runs a daycare. Asked lots of questions about our health care policy, citing multiple different health problems that she has.",
    "reference_check": "Rosanna’s employees at Rob & Bob’s Pizza Buffet talk about what a hard-worker she is, although none of them liked her on a personal level all that much. The owners never had to worry about the restaurant being run efficiently, or its cleanliness when she was there, but there were a few cases of lower level employees quitting because they did not like working for her."
  },
  {
    "repId": "rep9",
    "name": "Rhonda Blalock",
    "gender": "F",
    "education": "BSBA, Ohio State University",
    "experience": "3 years selling jewelry",
    "intelligence": 54,
    "myers_briggs": "INFJ",
    "other_info": "Breeds Horses",
    "interview": "Rhonda has a rather unique personality. Appeared nervous at first, and came on a little strong. Was extremely well prepared for the interview. Knew the ins-and-outs of our company, and was surprisingly knowledgeable about aromatherapy. Very excited to get her foot in the door of this industry while it’s relatively new.",
    "reference_check": "References all state that Rhonda is well liked by customers; however, she could sometimes be a bit much for her co-workers. When it came to her work, she was always great. Her passion for horses could be a bit overwhelming to people at times, as she is constantly talking about them."
  },
  {
    "repId": "rep10",
    "name": "Terry Brady",
    "gender": "F",
    "education": "BS Education, University of Michigan",
    "experience": "Started own media company while still in college, ran it for over a decade, sold the company last year and is looking for a new challenge",
    "intelligence": 96,
    "myers_briggs": "ESTJ",
    "other_info": "Star athlete in basketball and golf for high school in Swampscott, MA",
    "interview": "Very bright, big brained individual. Comes on strong, but after talking for a few minutes, Terry clearly came across as the smartest person in the room. Built media company brick by brick from the ground up. Planned on selling the company and retiring, but simply could not stop working, so is now looking for a new challenge.",
    "reference_check": "Former employees back up everything about their old boss. Although tough to work for sometimes, Terry always got the best out of employees. Despite intimidating levels of intelligence, Terry is still by all accounts a salt-of-the-earth team player."
  },
  {
    "repId": "rep11",
    "name": "Tori Braxton",
    "gender": "F",
    "education": "BS Sales Management, University of Baylor",
    "experience": "4 years construction sales",
    "intelligence": 46,
    "myers_briggs": "ENTJ",
    "other_info": "Avid fisherman. Has won multiple local fishing competitions",
    "interview": "Tori is a southern girl who loves being outdoors. Brought lots of energy to the interview, great smile, and made appropriate eye contact as well. Very direct, and to the point. Wasn’t afraid to ask specific questions about how the business is run, how she’s going to be able to succeed, and how much money she’ll be making.",
    "reference_check": "Tori’s last boss thought she was a fantastic salesperson. Would always go above and beyond to lock down business. As a lover of the outdoors, Tori would often close deals on fishing trips, hunting trips, and on the golf course as well. Despite working in the construction industry, which is traditionally dominated by men, Tori fit right in.  Was consistently a top performer."
  },
  {
    "repId": "rep12",
    "name": "Thom Bromly",
    "gender": "M",
    "education": "BSBA, University of Cincinnati",
    "experience": "3 years accounting, Deloitte",
    "intelligence": 54,
    "myers_briggs": "ENTP",
    "other_info": "Uses a flip phone and carries a pocket calculator",
    "interview": "Thom is a bit of a strange person. He made good eye contact during the interview, asked good interview questions, and has an impressive educational background. Seems to be over qualified for sales, but says he is tired of monotonous accounting work and is looking for a job where he can interact with people more.",
    "reference_check": "Thom had a 3.9 in college at the University of Cincinnati, and was the captain of the Club Chess team. His bosses at Deloitte gave Thom positive reviews, but said he was a fairly quiet person, and did not talk to a lot of his co-workers. Although quiet, Thom is a fast learner, and his former bosses believe he could be a fine salesperson if given the right training."
  },
  {
    "repId": "rep13",
    "name": "Trinity Brown",
    "gender": "F",
    "education": "1 year Amherst Catholic College",
    "experience": "5 years as clerk at the local bookstore",
    "intelligence": 20,
    "myers_briggs": "INTP",
    "other_info": "Rebelled against her parents by dropping out of Bible college",
    "interview": "Very quirky individual. Made an awkwardly excessive amount of eye contact during the interview that made everybody feel uncomfortable. Resume was printed on blue paper.",
    "reference_check": "The general consensus on Trinity is that she is a pretty weird person. She was fired from her last job at the bookstore, which she failed to mention on her application or in the interview. She does do a large amount of charitable work for her church, and works at a soup kitchen most weekends."
  },
  {
    "repId": "rep14",
    "name": "Kelly Byers",
    "gender": "F",
    "education": "Associate Degree, Management - Wing State",
    "experience": "4 years at Forever 21",
    "intelligence": 38,
    "myers_briggs": "INTJ",
    "other_info": "4th place in National Collegiate Mediation Competition",
    "interview": "Fairly nice for the most part. For some reason she got a bit annoyed when we asked her about her 5 year plan. Aside from that she was very engaging, and easy to talk to. Kelly’s job at Forever 21 was not meant to be a sales position, she says she could always get a customer to buy something when they walked in the store.",
    "reference_check": "Kelly did not provide any personal references, only references from her time at Forever 21. Kelly’s bosses liked her because she showed up to work on time and was a hard-worker for the most part. Kelly’s co-workers did not like her so much. They said she was “full of herself” and that she “wasn’t as great as she thought she was.”"
  },
  {
    "repId": "rep15",
    "name": "Antonio Canseco",
    "gender": "M",
    "education": "BA Communications, Colorado University",
    "experience": "4 years car salesperson, 2 years working at a store called Tamara’s Herbs ‘n Stuff",
    "intelligence": 42,
    "myers_briggs": "ENTP",
    "other_info": "Refurbishes classic cars in his garage on the weekends",
    "interview": "Of all the people we interviewed, Antonio is one of the only ones with previous experience selling aromatherapy products. He is very knowledgeable in the field, and has especially friendly demeanor.  He may have spaced out once or twice during the interview, but overall we were very impressed with his product knowledge and passion for the job.",
    "reference_check": "Antonio was fired from his job as a car salesperson, despite having some of the best sales numbers in the region. Antonio simply found the job boring, would show up late, and call in sick once a month. References from prior employers were all glowing. One boss said Antonio never missed a day of work, and as long as they were busy enough to keep him engaged he would be a fantastic worker. Could always talk the customer into buying additional product."
  },
  {
    "repId": "rep16",
    "name": "Autumn Carrasco",
    "gender": "F",
    "education": "BA, Fashion Merchandising, Kent State University",
    "experience": "Waitress for 5 years at Fricker’s Sports Bar",
    "intelligence": 46,
    "myers_briggs": "ISFP",
    "other_info": "Lived in Paris for a brief time; has had a couple modeling stints",
    "interview": "Very tall woman with very expensive clothes. Carried herself with confidence. Rarely smiled. Talked in a very serious tone. All business type of personality. Asked if she could record the interview on her phone, but fully understood why we could not allow that.",
    "reference_check": "Autumn’s bosses and co-workers at Fricker’s said that Autumn was an exceptional worker, but did not always have a good attitude. As a waitress, Autumn consistently received the lowest tips because she rarely smiled, and did not make any effort to establish a rapport with her tables."
  },
  {
    "repId": "rep17",
    "name": "Devin Carter",
    "gender": "M",
    "education": "BSBA, Louisiana State University",
    "experience": "5 years as a pharmaceutical sales rep",
    "intelligence": 64,
    "myers_briggs": "ISTJ",
    "other_info": "Talented saxophone player. Plays in a blues band on the weekends",
    "interview": "Interesting applicant. Clearly a very smart man. Preached hard work during the interview, very competitive attitude. Seems to have a real passion for making money for himself as well as his business.",
    "reference_check": "Positive reviews from his co-workers in the pharmaceutical industry. Hard worker, takes his business very seriously."
  },
  {
    "repId": "rep18",
    "name": "David Catz",
    "gender": "M",
    "education": "BSBA & English Minor, University of Wisconsin Madison",
    "experience": "5 years both writing and selling ad space for the Chicago Tribune",
    "intelligence": 60,
    "myers_briggs": "ESFJ",
    "other_info": "Recently sold his share of the vape shop “Planet of the Vapes” in Chicago, Illinois",
    "interview": "Very likeable guy. Makes a great first impression. Very large man, but carries himself well. Is looking forward to having a single job where he can focus solely on sales instead of juggling.",
    "reference_check": "Great all around guy according to references. Former co-workers at the Chicago Tribune referred to David as a real Jack of All Trades. The fellow owners of “Planet of the Vapes”, mentioned how he also did most of the bookkeeping for the business as well."
  },
  {
    "repId": "rep19",
    "name": "Rico Chaisson",
    "gender": "M",
    "education": "BS, Agricultural Sciences, University of Hawaii",
    "experience": "10 years as a surf instructor",
    "intelligence": 34,
    "myers_briggs": "INTP",
    "other_info": "Obviously a skilled surfer, knows water (oceans) well",
    "interview": "Tall, tan, handsome man with long flowing black hair. Incredibly charming personality. Has been selling his services as a surfing instructor for over a decade, and Rico believes having his own business for so long where he interacted with different people on a daily basis will make him a great salesperson",
    "reference_check": "Rico’s references were essentially a list of his best surf school clients. All clients we contacted said that Rico was a fantastic surf teacher. Most all of his former clients say that he helped them fall in love with surfing, and they still surf on a regular basis up to this day."
  },
  {
    "repId": "rep20",
    "name": "Diana Christopher",
    "gender": "F",
    "education": "High School Education",
    "experience": "12 years working for her father’s bakery",
    "intelligence": 36,
    "myers_briggs": "ENFP",
    "other_info": "Enjoys skiing, cross-country skiing, and snowshoeing",
    "interview": "Diana brought in cookies for the office when she came in for the interview. It was not the most professional move ever, but they were very well received. Admittedly nervous to work in sales, as she does not have much prior experience. Extremely nice, likeable, and easy to talk to.",
    "reference_check": "Diana’s references come from her father, and other employees of her father, so they all had great things to say about her. She has been working at the bakery since she was 13 years old, and knows everything there is to know about the business. Her father could always rely on her to open and close the shop, and co-workers could always go to her for help with anything they needed."
  },
  {
    "repId": "rep21",
    "name": "Tim Cobb",
    "gender": "M",
    "education": "Associate Degree, General Studies - Altadena College",
    "experience": "5 years floor sales at Urban Outfitters",
    "intelligence": 32,
    "myers_briggs": "ISFP",
    "other_info": "Buys items on eBay and resells them for more money",
    "interview": "Tim was a bit of a hipster, who did not come dressed to the interview in business professional attire like he was instructed. Tim says that in order to be good at sales, you have to feel good about yourself.  He says he does not feel like himself in a suit and tie. Changed the subject multiple times during the interview. Gave long-winded answers. Interview ended up taking 20 minutes longer than normal.",
    "reference_check": "References from Urban Outfitters we’re all positive. Customers never had complaints about Tim. He was very helpful and not too pushy. Would sometimes forget what day/time he was supposed to work, but whenever he forgot, he would come in as soon as they called and reminded him."
  },
  {
    "repId": "rep22",
    "name": "Bethany Cobblestone",
    "gender": "F",
    "education": "Temecula Career Center Veterinarian School",
    "experience": "2 years as a vet assistant",
    "intelligence": 26,
    "myers_briggs": "ISTP",
    "other_info": "The vet Bethany recently worked under was fired for malpractice",
    "interview": "Bethany comes across as a very nervous person. Voice was shaky during the interview. Expressed the fact that she really needs a job right now. Made sure several times we knew that Bethany had nothing to do with the malpractices that occurred under the Vet she was working for.",
    "reference_check": "The references checked out. Bethany had nothing to do with the Veterinary clinic being shut down. She was simply an assistant there. Bethany’s personal references all dwell on what a sweet girl she is, and how great her family is. However, nobody talked about how smart she was, or how hard of a worker she was."
  },
  {
    "repId": "rep23",
    "name": "Yolanda Connors",
    "gender": "F",
    "education": "Associate Degree in Theatre, Los Angeles Community College",
    "experience": "3 years working behind the scenes of movies and television shows, along with several years of part-time retail experience",
    "intelligence": 38,
    "myers_briggs": "INTJ",
    "other_info": "Giving up her dream of being a movie star and is looking to move to the Midwest. Fluent in Spanish",
    "interview": "We had to conduct a phone interview with Yolanda as she is currently out in California. She was very articulate and confident over the phone. No prior sales experience, but Yolanda believes that living in California where aromatherapy is more prominent will give her an advantage selling the product in Ohio.  A great listener!",
    "reference_check": "Yolanda’s prior supervisor said that she would regularly come up with creative solutions to make process more efficient.  Relative to coworkers, she was always more interested in the business part of show-business. In her one movie role (a nonspeaking role in a Disney movie), she was said to be very cooperative and professional."
  },
  {
    "repId": "rep24",
    "name": "Morgan Cosfree",
    "gender": "M",
    "education": "Associates in Marketing, Great Bay Community College",
    "experience": "4 years insurance salesperson at Liberty Mutual",
    "intelligence": 44,
    "myers_briggs": "ESTP",
    "other_info": "Calls his past DUI charge a momentary lapse in judgment.",
    "interview": "Morgan is very likeable. Display’s a great deal of confidence. Easy to talk to and relates very well with people on a personal. Although he did not have the best answers to the interview questions, he was well liked by everyone he met at the interview and overall it went very well.",
    "reference_check": "Aside from the DUI, background check and references were very positive. Former employers cited how well he was liked by his co-workers, and how he received almost exclusively positive reviews from his customers."
  },
  {
    "repId": "rep25",
    "name": "Maria DeSilva",
    "gender": "F",
    "education": "GED",
    "experience": "17 year used car salesperson",
    "intelligence": 26,
    "myers_briggs": "ISFP",
    "other_info": "Has starred in local commercials for Troy’s Used Car Lot",
    "interview": "Maria was a fairly quiet person. Not very well prepared for the interview. Asked very few questions, and did not make eye-contact during the interview. Had a recent falling out with her father for refusing to be in any more of his used car commercials, so now she is looking for a new job.",
    "reference_check": "Starting selling used cars right out of high school for her father Troy’s used car lot. Maria actually had some of the highest sales numbers in the company, but co-workers say this is due to her attractiveness, and her dad sending her all of the good customers"
  },
  {
    "repId": "rep26",
    "name": "Hannah Dixon",
    "gender": "F",
    "education": "Associate Degree, Fashion, New York Community College",
    "experience": "4 years at Victoria’s Secret",
    "intelligence": 24,
    "myers_briggs": "ISFP",
    "other_info": "Has her own business putting up and taking down Christmas lights for houses in her community",
    "interview": "Showed up 15 minutes late for the interview. Said it was due to bad traffic on the interstate. The interview itself went well. Hannah was likeable, fairly easy to talk to, but was certainly not the brightest person we have interviewed. Provided excessive amount of references dating back to junior high, which was weird as well.",
    "reference_check": "Hannah has a large amount of positive reviews. She has been well known in the community for years for her Christmas lights business. Put in a lot of work each holiday season to get her company name out there and acquire new customers. At Victoria’s Secret, Hannah had a reputation of showing up late to work. She almost never missed a shift, but also rarely showed up earlier than 10 minutes late."
  },
  {
    "repId": "rep27",
    "name": "Winston Druthers",
    "gender": "M",
    "education": "GED",
    "experience": "2 years at AutoZone",
    "intelligence": 36,
    "myers_briggs": "ENFP",
    "other_info": "Favorite thing to do is drinking beer while watching football on TV",
    "interview": "We discovered that Winston was fired from AutoZone for taking money from the cash register as well. His boss at AutoZone says that up until Winston was caught stealing money, he was a below average employee.",
    "reference_check": "We discovered that Winston was fired from AutoZone for taking money from the cash register as well. His boss at AutoZone says that up until Winston was caught stealing money, he was a below average employee. Personal references said that Winston used to have drug problems. They think he is better now, but are not sure."
  },
  {
    "repId": "rep28",
    "name": "Hannibal Forrester",
    "gender": "M",
    "education": "BS - Public Relations, Texas Christian University",
    "experience": "6 years at Pizza Hut",
    "intelligence": 44,
    "myers_briggs": "ISTJ",
    "other_info": "Does improvisational comedy on Tuesday nights at the Funny Bone",
    "interview": "Comes on a bit strong. Hannibal is a very happy person who likes to crack jokes, but his jokes were not all that funny and some were inappropriate for the setting. However, he was well prepared for the interview, he took lots of notes and impressed us with his knowledge of our company.",
    "reference_check": "Hannibal was a true jack of all trades at the local Pizza Hut. He came into work every day not knowing if we was going to be working in the kitchen, serving, or delivering pizzas. He often filled in for managers as well when they could not make it in. Co-workers liked working with him because they knew he would carry his weight, but did admit that his jokes were annoying at times."
  },
  {
    "repId": "rep29",
    "name": "Eddie Fox",
    "gender": "M",
    "education": "BS - Education, Boise State University",
    "experience": "5 years teaching High School",
    "intelligence": 42,
    "myers_briggs": "ESTJ",
    "other_info": "As a teacher Eddie was the leader of the Senior Marketing Club",
    "interview": "Eddie is a fair prospect. He is currently interviewing for several sales jobs. Eddie has spent his career teaching high school up to this point, but is tired of the low pay and thinks he is capable of making more money in a job with commission. He does have a passion for marketing, and would like to work in that area someday.",
    "reference_check": "Teachers and Administrators at Eddie’s high school all like Eddie very much as a person, and say he is a hard worker, but he isn’t the best teacher at all times. Has a tendency to do his own thing as opposed to following the curriculum directly as he should be. They all seemed to think Eddie may be a much better fit in sales."
  },
  {
    "repId": "rep30",
    "name": "Stevie Gonger",
    "gender": "M",
    "education": "BS General Studies, Western Michigan University",
    "experience": "8 year pro shop manager at Western Michigan University Ice Arena",
    "intelligence": 48,
    "myers_briggs": "ESFJ",
    "other_info": "Played 4 years for the Western Michigan club hockey team, can drive a Zamboni",
    "interview": "Makes a strong first impression, partly due to what seemed to be a thick Canadian accent, even though Stevie was born in Ohio. Very sharp dressed man with a unique personality. Laughs a lot. Does not have any direct experience with sales, but has dealt with customers at the University ice arena on a daily basis for the last several years.",
    "reference_check": "Previous employers and coaches say how Stevie is a natural born leader. Often times he takes the lead on things like end of the year Holiday parties, work/team vacations, weekend get-togethers, etc. Stevie’s boss at the ice arena says that customers would specifically as for him when they had questions about their skates and/or equipment"
  },
  {
    "repId": "rep31",
    "name": "Melanie Harrison",
    "gender": "F",
    "education": "BA, Marketing, University of Cincinnati",
    "experience": "3 years as Sales Representative for Verizon Wireless",
    "intelligence": 46,
    "myers_briggs": "ENTP",
    "other_info": "Free-lance writer for local newspaper in Ohio, has a number of published articles",
    "interview": "Melanie is quite pleasant, but does not come across as an exceptionally hard worker. Dressed in very hip fashion, not necessarily business professional. Is excited to work a job with more freedom as opposed to being stuck inside a Verizon Wireless store all day. She claims to be very good at negotiating deals.",
    "reference_check": "Previous employer at Verizon Wireless say Melanie’s numbers were “par for the course.” Sometimes she had problems with up selling customers on certain data packages if she didn’t personally think they sounded like a good deal. Could be too idealistic at times, but was a very hard worker nonetheless."
  },
  {
    "repId": "rep32",
    "name": "Gregory Howe",
    "gender": "M",
    "education": "Associate's in Business, Centennial College (Toronto, CA)",
    "experience": "1 year inside ticket sales with the Toronto Maple Leafs, 4 years as a car salesperson in Toronto, Canada",
    "intelligence": 72,
    "myers_briggs": "ENFP",
    "other_info": "Family owns several Tim Horton’s in the greater Toronto area",
    "interview": "Very friendly, down to earth guy. Comes off as a “good ol’ boy” type with a very thick Canadian accent as well. Gave great answers to all questions asked of him, but most impressive is how he was able to relate to everyone in the room on a personal level as well.",
    "reference_check": "Seems that everyone who has ever dealt with Gregory in business or in his personal life really loves the guy. Worked at his parents Tim Horton’s since he was 13 years old. Pursued an Associate’s Degree as opposed to a 4 year degree so he could have more time to help with the family business. Has lots of hobbies, and very high morals as well."
  },
  {
    "repId": "rep33",
    "name": "Brandon Howschwitz",
    "gender": "M",
    "education": "BA, Economics, Mississippi State University",
    "experience": "3 years as a cashier at Dick’s Sporting Goods, 2 years as a Janitor on campus",
    "intelligence": 62,
    "myers_briggs": "INTP",
    "other_info": "Teacher’s Assistant for a couple of his Professors on campus",
    "interview": "Fine young man. Brandon admits that he would prefer a job as an economist, but has been struggling to find any work post graduating college. Recently decided that sales is something he could do pretty easily, so he figures he will find a sales job to hold him over until something better comes along",
    "reference_check": "The professors Brandon assisted both agreed that as a student, Brandon was a bit of an underachiever. His GPA in college was 2.0, but his teachers think he almost never studied or put forth any real effort. Managers at Dick’s sporting good echo his teacher’s thoughts. More than capable of doing anything he puts his mind to."
  },
  {
    "repId": "rep34",
    "name": "Wendy Hoyt",
    "gender": "F",
    "education": "High School Education & 2 years at Eastside Daniel’s Finishing School",
    "experience": "19 years as a nanny for multiple different families",
    "intelligence": 30,
    "myers_briggs": "ENTP",
    "other_info": "Spent one year in jail for tax evasion",
    "interview": "Very sweet lady, been out of jail for 3 years and has been struggling for new business in the nanny game ever since. Seems to be genuinely remorseful, yet we had the sense that she was keeping something from us.",
    "reference_check": "All of her former clients loved her, and say that she was great with kids. Despite her past legal issues, she now seems to be very well liked, even respected in her community."
  },
  {
    "repId": "rep35",
    "name": "Jennifer Huntley",
    "gender": "F",
    "education": "High School",
    "experience": "Worked for the city department for 22 years in San Antonio",
    "intelligence": 40,
    "myers_briggs": "ISFP",
    "other_info": "Has a cattle ranch and is known for equestrian activities with her horses",
    "interview": "Jennifer is a wholesome, enthusiastic woman. Everyone she met at the interview loved her personality. She loves being outside, and does not want to be cooped up in an office all day. Says that people have always encouraged her to get into sales because they think she would be good at it, and Jennifer is finally ready to give it a try.",
    "reference_check": "Fellow city workers all love Jennifer. They’ve been encouraging her to leave for over 5 years now, because she was not living up to her potential working for the city. Her direct boss says she will be great in sales because she is able to relate to anyone, and it’s impossible not to like her."
  },
  {
    "repId": "rep36",
    "name": "MaryJane Walters",
    "gender": "F",
    "education": "BS Supply Chain Management, University of Kansas",
    "experience": "3 years sales, 3 years sales management with Owens Corning",
    "intelligence": 36,
    "myers_briggs": "ENFJ",
    "other_info": "1st place in University of Kansas Sales Competition",
    "interview": "Delightful person. Very easy to talk to. Very energetic and prepared. Perhaps a bit loud if anything, but it was in a fun way. MaryJane is excited about this new industry in Ohio, and thinks aromatherapy candles will be the perfect product for her to sell. Owens Corning was getting a little boring for her tastes.",
    "reference_check": "MaryJane admits that she has made some bad choices in the past, especially when drinking in public -- but promises, \"Those days are behind me.\"  Past co-workers say she is lots of fun.  She had high sales number at Owens Corning when she was a sales rep, and her team has had exceptional numbers ever since MaryJane took over at manager as well."
  },
  {
    "repId": "rep37",
    "name": "Marshall Jordie",
    "gender": "M",
    "education": "BSBA, University of North Carolina",
    "experience": "10 years working with Nike. Started in customer support, moved on to sales within the first year after discovering a knack for it early on.",
    "intelligence": 66,
    "myers_briggs": "ENTJ",
    "other_info": "Worked to register voters for election this year, and managed to not once reveal who he was voting for. Claims that even his best friends don’t know.",
    "interview": "Very impressive individual. One of the best dressed candidates we have ever had apply for this position. Asked great questions, some so good that we did not even know the answers too. Gave a firm handshake. Impressed everyone in the room, strike you as the kind of man you want to do business with.",
    "reference_check": "Nike cited how Marshall was a “born salesperson.” Knows how to be direct with people, doesn’t beat around the bush, and gets right to the close. Doesn’t dwell on missed opportunities, is always moving forward and looking to expand his business."
  },
  {
    "repId": "rep38",
    "name": "Tobias King",
    "gender": "M",
    "education": "BSBA, University of Illinois",
    "experience": "4 year salesperson & 6 years sales manager at Petco",
    "intelligence": 50,
    "myers_briggs": "ISTJ",
    "other_info": "Loves to play chess and watch Jeopardy",
    "interview": "Tobias has a very calming presence about him. Seems like the type of guy you inherently trust. Appears to undervalue himself. Has a business degree from the University of Illinois, but was content to keep working at Petco",
    "reference_check": "Tobias said he left Petco for ethical reasons -- something about how the store lied about the health of the cats it was selling.  His bosses were sad to see him go. Customers and co-workers loved Tobias, and always knew to go to him with any questions they had. When he quit, they offered him a promotion where he would be overseeing multiple Petcos, but he declined."
  },
  {
    "repId": "rep39",
    "name": "Brian Lafevre",
    "gender": "M",
    "education": "BSBA, Temple University",
    "experience": "5 years Account Executive for Duracell",
    "intelligence": 40,
    "myers_briggs": "INFJ",
    "other_info": "Active in the local open mic/music scene and poetry clubs",
    "interview": "Brian was a very likeable and confident guy. He talked a lot about music and art. Sold batteries for Duracell for 5 years before quitting to focus on work in the music industry. He helps promote local artists by finding them stage time and locations to sell CD’s and merchandise. Since quitting Duracell, the music industry hasn’t been paying the bills, so Brian is in need of a full-time job again.",
    "reference_check": "Very well respected man in the community. Popular local acts give credit to Brian to helping jumpstart their music careers. Previous bosses at Duracell all really liked Brian as well, and did not want to lose him when they did."
  },
  {
    "repId": "rep40",
    "name": "Shaniqua Lexington",
    "gender": "F",
    "education": "BS, Political Sciences University of Florida",
    "experience": "7 years as a Receptionist at a local dentist’s office",
    "intelligence": 48,
    "myers_briggs": "ISTP",
    "other_info": "A known activist on campus at the University of Florida",
    "interview": "Electric personality. Lights up the room when she walks in. Came very prepared with questions about the job. Admittedly had not been in a formal interview since she started at the dentist’s office 7 years ago. There were some rough patches during the interview, but Shaniqua was so likeable that it made up for her weak moments.",
    "reference_check": "All other employees at the dentist’s office loved working with Shaniqua. They all cited how she made work so much better with her hilarious personality. She was able to develop relationships with all co-workers, and most patients in the limited time she interacted with them."
  },
  {
    "repId": "rep41",
    "name": "Gina Mansfield",
    "gender": "F",
    "education": "Associate Degree, History",
    "experience": "7 years at Jo-Ann Fabrics",
    "intelligence": 40,
    "myers_briggs": "ENTP",
    "other_info": "Knits sweaters for pets such as dogs, cats, and birds",
    "interview": "Gina is a pleasant lady. Didn’t make a big first impression. Very laid back personality, yet was focused on the interview. No prior sales experience aside from helping out customers at Jo-Ann Fabrics. Resume was not very full, but Gina came across as being sharp, and capable of learning.",
    "reference_check": "References took a minute to remember who Gina was, but once they recalled, they had mostly positive things to say. By all accounts she would show up to work on time and do a fine job while she was there. If there’s a knock on Gina, it is that she is a forgettable person, without much of a personality."
  },
  {
    "repId": "rep42",
    "name": "Heather Marowick",
    "gender": "F",
    "education": "High School Education",
    "experience": "5 years as an Instagram model",
    "intelligence": 24,
    "myers_briggs": "ENFP",
    "other_info": "Also applying for cosmetology school",
    "interview": "Heather was an interesting interview. Made demands regarding the time off she would need for the job in order to continue her modeling career and start cosmetology school. Seemed very unorganized. Had lots of questions for us, but dismissed questions we asked her.",
    "reference_check": "Both personal and professional references state that Heather can be high maintenance at time. She is by all accounts a very fun person to be around, and can be smart when she applies herself, but those times are few and far between."
  },
  {
    "repId": "rep43",
    "name": "Roy McFreely",
    "gender": "M",
    "education": "Associate Degree, Business Ethics, Appalachian Community College",
    "experience": "2 year liquor salesperson for Captain Morgan",
    "intelligence": 28,
    "myers_briggs": "ISTP",
    "other_info": "Has his own Roy McFreely brand alcoholic energy drink, Roy-Max",
    "interview": "Brought tons of energy to the interview. Very confident young man, with lots of ideas. A bit sporadic with his thoughts. Went off on a couple long tangents during our conversation. We wondered if he had consumed a few Roy-Max’s before coming in! Roy believed that his experience selling liquor would translate well to aromatherapy products. We asked him to elaborate on that, but he could not.",
    "reference_check": "Sold a very impressive amount of Roy-Max’s when the drink first hit the market, despite its horrible taste (he brought us some to take home at the interview). Also sold Captain Morgan, but provided no references so we could not look into his performance at that job."
  },
  {
    "repId": "rep44",
    "name": "Ishmael Mohammed",
    "gender": "M",
    "education": "2 years Memphis University",
    "experience": "6 years floor salesperson at Best Buy",
    "intelligence": 52,
    "myers_briggs": "ENFP",
    "other_info": "Plays in a local adult soccer league as a goalie",
    "interview": "Ishmael comes across as a very intelligent man, but his people skills may be lacking a bit. He was not the easiest person to talk to, but he provided fairly impressive answers to all of our questions.",
    "reference_check": "Previous employers also cited how Ishmael was a very bright individual, who did not necessarily have the best people skills. At Best Buy, he was able to answer any questions the customers had, but sometimes had a hard time articulating the answer in a way that the customer would understand. Knowledgeable customers loved him, but those who were not so familiar with electronics would sometimes get frustrated."
  },
  {
    "repId": "rep45",
    "name": "Nikki Monroe",
    "gender": "F",
    "education": "BS Tourism & Hospitality, Arizona State University",
    "experience": "2 years in the Hospitality industry working for the Four Seasons in Phoenix",
    "intelligence": 60,
    "myers_briggs": "INTJ",
    "other_info": "Does work organizing events for the Arizona State University Alumni Association",
    "interview": "Very nice woman. Makes a great first impression, good eye-contact, and nice smile. Came across as professional and very comfortable in the interview process.",
    "reference_check": "Nikki has a great track record of working hard, showing up on time, and going above and beyond for her employers. Fellow employees at the Four Seasons say Nikki had a knack for getting hotel guests to upgrade their tourist packages."
  },
  {
    "repId": "rep46",
    "name": "Ricardo Montague",
    "gender": "M",
    "education": "3 years North Dakota State University",
    "experience": "3 year floor salesperson at Sears",
    "intelligence": 38,
    "myers_briggs": "ISTP",
    "other_info": "Just returned from two years backpacking overseas.",
    "interview": "Enthusiastic person. Has a new lease on life since returning to the states. Says he’s very organized and has always been good at managing his time.",
    "reference_check": "Before travelling, he was a floor salesperson at Sears, where he was a fair employee that never caused problems. The few references we could contact from odd jobs during his travels said he was friendly and intelligent, but mentioned that his work ethic sometimes slipped because he was distracted by his next adventure."
  },
  {
    "repId": "rep47",
    "name": "Rachel Ngatori",
    "gender": "F",
    "education": "BSBA, University of Louisville",
    "experience": "5 years public relations for General Mills",
    "intelligence": 50,
    "myers_briggs": "ENTJ",
    "other_info": "President of the Asian Culture club at Louisville",
    "interview": "Nice girl. Seems to be good with people in general. Does not have an exceptionally confident personality. Rachel kept saying she was sorry for her poor answers to our questions, yet her answers were solid for the most part.",
    "reference_check": "All of her references said that Rachel was looking for other work. She seemed to be well liked by all of her former co-workers, although they were surprised that Rachel was looking for a sales job, because she was such a good fit in Public Relations at General Mills"
  },
  {
    "repId": "rep48",
    "name": "Veronica Nightingale",
    "gender": "F",
    "education": "BS Business Marketing, University of Maryland",
    "experience": "9 years outside sales for a mid-range paper supply firm",
    "intelligence": 44,
    "myers_briggs": "ESTJ",
    "other_info": "Currently obtaining her helicopter license",
    "interview": "Veronica has an intimidating presence about her. Essentially directed the interview herself, and she was great at steering the conversation to where she wanted it to go. Did not bring anything to take notes with during the interview, but answered questions well, and even tried to close at the end of the interview.",
    "reference_check": "Aside from a couple complaints to HR regarding foul language used at office Holiday parties, former employers and co-workers had great things to say about Veronica. She was always a big personality at work when she was in the office, and people tended to gravitate to her. Although she is unorganized, and occasionally forgetful, she consistently had some the of the highest paper sales numbers in the company."
  },
  {
    "repId": "rep49",
    "name": "Carl Norfish",
    "gender": "M",
    "education": "Associate Degree General Studies, Bison Community College",
    "experience": "7 years selling medical supplies, inside sales",
    "intelligence": 42,
    "myers_briggs": "ISTJ",
    "other_info": "Hobbies include cooking and running marathon",
    "interview": "A bit of an awkward interview. Carl is fairly monotone and deliberate in the way he speaks which was a bit off-putting. Carl is used to dealing with doctors and administrators in the field of health care, so moving to this industry may be a bit of a culture shock for him.",
    "reference_check": "Carl’s references echo our thoughts on him as well. A bit of a different kind of guy who is not always easy to talk to. However, Carl’s sales numbers were always middle of the road, and he rarely got complaints from customers. His direct boss described Carl as “exceptionally average.”"
  },
  {
    "repId": "rep50",
    "name": "Bristol O'Callahan Sr.",
    "gender": "M",
    "education": "GED",
    "experience": "3 years selling Envigra Health Beans",
    "intelligence": 28,
    "myers_briggs": "INFP",
    "other_info": "Trains show dogs on the weekends",
    "interview": "Bristol is a burly man who does not smile much. Seemed like he did not really want to be at the interview. Gave a lot of one-word answers. Supported himself selling Envigra Health Beans for 3 years before he realized it was a pyramid scheme and pulled his money out.",
    "reference_check": "Only references he provided were the numbers of the dog owners that he trains. The owners all had great things to say about his work, except that he could sometimes be mean.  Nobody in the community seems to know him as a person."
  },
  {
    "repId": "rep51",
    "name": "Carmen O'Malley",
    "gender": "F",
    "education": "BS, Aeronautical Engineering, Air Force",
    "experience": "15 years working at local Air Force hanger",
    "intelligence": 58,
    "myers_briggs": "ENTP",
    "other_info": "Has a pilot’s license and flew some while at Air Force, 5 years with ROTC",
    "interview": "Carman was a very nice woman who recently finished serving her time in the Air Force and would like to get into sales. After a life full of strict rules and policies to follow, she says she is ready for something different.  She thinks the aromatherapy industry might be just the place for her.",
    "reference_check": "The Air Force spoke incredibly high of Carmen’s dedication to work. In the service, Carmen had an excellent reputation for punctuality and being well organized. She wasn’t necessarily the best at her job, but she did everything in her power to get a little bit better every day."
  },
  {
    "repId": "rep52",
    "name": "Terrance Olley",
    "gender": "M",
    "education": "BSBA, University of Toledo",
    "experience": "Internship with Marathon during senior year at University of Toledo",
    "intelligence": 52,
    "myers_briggs": "ENTJ",
    "other_info": "President of his Fraternity",
    "interview": "Terry is a confident young man, but it’s clear that he has not been to very many interviews in his life. It’s clear that Terrance is a smart person, but was not overly prepared for the interview and did not ask great questions at the end. At the same time, Terrance seemed very capable and expressed an eagerness to learn.",
    "reference_check": "Mostly good reviews. Terrance’s personal references cited what a great family and group of friend’s Terrance keeps around him. His boss at Marathon liked him as well. He mentioned that Terrence could be a little unorganized at times, especially at the beginning of the internship, but by the end his organizational skills had greatly improved."
  },
  {
    "repId": "rep53",
    "name": "Camille Parker",
    "gender": "F",
    "education": "BS Communications, University of Tennessee",
    "experience": "2 years telemarketing, 3 years in Pharmaceutical sales",
    "intelligence": 40,
    "myers_briggs": "ESFJ",
    "other_info": "Spent 1 year post-college traveling in Europe, Asia, and Australia",
    "interview": "Delightful interview with a great person. Camille is able to be genuinely funny, yet professional at the same time. She claims to be a fitness fanatic.  Answered questions appropriately and asked good questions as well.",
    "reference_check": "Past employers all loved Camille as she worked for them, but complained how she left her jobs fairly abruptly. Aside from that, she was a great employee with a knack for closing deals. Both former employers cited her very high customer review scores."
  },
  {
    "repId": "rep54",
    "name": "Brady Ranger",
    "gender": "M",
    "education": "2 years Fresno State University",
    "experience": "none",
    "intelligence": 30,
    "myers_briggs": "ENFP",
    "other_info": "Drafted in the 40th round of the MLB draft in 2010, but recently gave up baseball",
    "interview": "Nice guy, with a competitive personality. He recently got cut from his minor league baseball team, and is looking for a regular job that would also feed his need to compete. Brady says he is finally ready to live a “normal life.”",
    "reference_check": "Brady did not graduate from Fresno State, and rarely attended classes the two years he was there. His coaches and teachers say he was always certain that he would play professional baseball, so he never took anything else seriously. They do believe that Brady has the attitude to be successful in whatever he does, as long as he puts forth the effort."
  },
  {
    "repId": "rep55",
    "name": "Hank Rolands",
    "gender": "M",
    "education": "High School Education",
    "experience": "22 years telemarketing",
    "intelligence": 34,
    "myers_briggs": "INFP",
    "other_info": "Spent 3 month in the Peace Corps before quitting; collects Rolex watches",
    "interview": "A bit of a contentious interview. Hank is a proud man who did not take kindly to us when we asked tough questions.  Hank thinks very highly of himself because he has been able to hold down the same job for over 2 decades",
    "reference_check": "Hank’s professional references state that he is a capable employee, but does not respond well to authority, and does not like adhering to strict guidelines. He likes to work by himself and does best when he’s given time to figure things out on his own. Personal references say that Hank can be a bit much to take at first, but once you get to know him you start to get used to it."
  },
  {
    "repId": "rep56",
    "name": "Topanga Rusicallo",
    "gender": "F",
    "education": "BA Fine Arts, University of Oklahoma",
    "experience": "7 years selling artwork",
    "intelligence": 52,
    "myers_briggs": "ENTJ",
    "other_info": "Topanga is an artist herself, specializing in impressions",
    "interview": "Topanga has a bright bubbly personality. Quirky at times, but likeable as well. Admittedly all of her sales experience comes from being a freelance art salesperson, and is looking for something more stable. Topanga still wants to continue painting impressions as a hobby, but wants to work in a more structured industry.",
    "reference_check": "Topanga references were limited as she has worked primarily for herself for the last 7 years. The references she did have were some of her biggest art customers. All gave her glowing reviews, citing how incredibly organized and reliable she was."
  },
  {
    "repId": "rep57",
    "name": "Dakota Sandersmith",
    "gender": "M",
    "education": "1 year at University of Wisconsin-Milwaukee",
    "experience": "5 years at TSC Tractor Supply",
    "intelligence": 22,
    "myers_briggs": "ISFP",
    "other_info": "Umpires High School baseball in the summer",
    "interview": "Dakota has a very loud and vivacious personality. He’s the kind guy you want to be friends with. Very nice. Great listener. Asked terrific questions and knew a lot about the industry. Dakota expressed how excited he was to work for us, and aspires to be the top salesperson in the company.",
    "reference_check": "Previous employers all loved Dakota as an employee. Dakota admitted in the interview that we might find a problem when we do a background check, but said he was pretty sure that enough time has elapsed so that the incident should be erased.  He did not elaborate."
  },
  {
    "repId": "rep58",
    "name": "Mike Schmeltz",
    "gender": "M",
    "education": "BSBA, Indiana University",
    "experience": "10 years working between the purchasing & marketing departments for the Dollar Shave Club. Responsible for identifying & purchasing ad space across a variety of platforms",
    "intelligence": 88,
    "myers_briggs": "ESTJ",
    "other_info": "Hobbies include gardening, volunteering and community service",
    "interview": "Strikingly beautiful mustache that makes you feel at ease as soon as he walks into the room. Great smile, took detailed notes throughout the interview, and was sure to follow up with questions on things we said that he did not fully understand at first. Asked what exactly he needs to do in order to get this job.",
    "reference_check": "At Dollar Shave club, Mike was the one who came up with the idea to advertise primarily on podcasts. Dollar Shave club considers this to be one of the best advertising moves they have ever made. They were sad to see Mike leave, but they both felt Mike had reached his full potential there."
  },
  {
    "repId": "rep59",
    "name": "Roberta Shadows",
    "gender": "F",
    "education": "1 year, Owens Community College",
    "experience": "3 years Sandwich Artist at Subway",
    "intelligence": 30,
    "myers_briggs": "INFP",
    "other_info": "Loves both horse riding and drawing",
    "interview": "Fun person to talk too. Has a great personality, but could not provide answers to most of our questions. Has not had any sales experience, but says she is good at making friends so she is sure she’ll be a great at sales.",
    "reference_check": "Co-workers at Subway all like to work with Roberta because she always has everything organized, and is a good conversationalist so work goes faster. She does however have a bad habit of messing up customer orders, and does not do math very well (according to the managers). Personal references also say she can space out at times."
  },
  {
    "repId": "rep60",
    "name": "Easton Shelley",
    "gender": "M",
    "education": "BS, Biology, University of Tulsa",
    "experience": "3 years as a Cashier at JC Penny’s, 1 year at local recycling center",
    "intelligence": 44,
    "myers_briggs": "INTP",
    "other_info": "Active in church, avid track and field athlete now and in college",
    "interview": "Nice, modest, humble individual. Was not especially comfortable talking about himself. Could tell he felt awkward when we said nice things about him, did not know how to take a compliment well.",
    "reference_check": "Easton is a quiet person by all accounts. Co-workers at JC Penny say that he rarely comes out of his shell and engages them in conversation. His superiors at JC Penny appreciate his timeliness and consistent work ethic."
  },
  {
    "repId": "rep61",
    "name": "Jasper Slawson",
    "gender": "M",
    "education": "BA, History, University of Wisconsin",
    "experience": "5 years at local movie theater as an usher, 2 years at movie rental store",
    "intelligence": 44,
    "myers_briggs": "INTP",
    "other_info": "Volunteers at local historic society, active with L.A.R.P (live-action role playing)",
    "interview": "Not very personable, but obviously smart. Asked a lot of specific questions about the people he will be working for and with. Was not concerned with salary and benefits. Was very concerned with what the work environment would be like.",
    "reference_check": "Jasper is known for being a particularly picky individual. He has been working in the movie rental store ever since he graduated from Wisconsin, has been offered multiple jobs in various different industries, but has turned down every one. He received great reviews from all previous employers. His current boss at the movie rental store does not understand why Jasper still works there."
  },
  {
    "repId": "rep62",
    "name": "Taylor Smith",
    "gender": "F",
    "education": "BS Sociology, Western Michigan University",
    "experience": "3 years as social worker in Michigan for the city of Kalamazoo.",
    "intelligence": 54,
    "myers_briggs": "ENTJ",
    "other_info": "Owns her own small business, Taylor’s Treats, where she makes and sells her own original desserts. Makes a small profit, but says she does it mostly for fun.",
    "interview": "Very nice, professional and prepared individual. Had well thought out answers to all interview questions. Loved her last job as a social worker, but is looking for more of a challenge, and thinks she would be great in sales.",
    "reference_check": "Always working, even when she’s not on the clock. Likes to keep busy at all times. Does not like to relax, which is typically good, but can sometimes be to a fault. Although her work ethic could at times be a bit over-bearing, all co-workers like and respect her, and think that her attitude is better fit for a sales role"
  },
  {
    "repId": "rep63",
    "name": "Fitzgerald St. James",
    "gender": "M",
    "education": "2 years at Duke University, Associates Degree in Sales from Smith-Brown-West Community College",
    "experience": "Took over his father’s tree selling business at age 20 and has been running it for the past 9 years",
    "intelligence": 44,
    "myers_briggs": "ESTP",
    "other_info": "Looking to sell his father’s business and start a new career",
    "interview": "Fitzgerald is well-dressed man with a fancy beard and mustache. He makes a great first impression. Very prepared for the interview. Was smart enough to get into Duke, but hated school so he dropped out. Sales is his number one passion in life. Says he is, “addicted to making money.” Asked extensive questions about how we structure commission. Is simply tired of selling Christmas trees and having to manage his own business.",
    "reference_check": "Fitzgerald St. James was born to be a salesperson. From the time he was young, his dad was teaching him how to upsell customers on Christmas trees. Co-workers say that he would often take a family who came to the lot for one Christmas tree, and talk them into buying two trees. One former colleague said he has quite a temper."
  },
  {
    "repId": "rep64",
    "name": "Montana Stone",
    "gender": "M",
    "education": "BS Management, University of Houston",
    "experience": "5 years sales with Sherwin WIlliams",
    "intelligence": 58,
    "myers_briggs": "ESFJ",
    "other_info": "Spent a year after college in the Professional Bull Riders league",
    "interview": "Very humble down to earth guy. Smart man, although he plays it down a bit. For some reason did not want to talk about his days as a professional bull rider. Very proud of the work he’s done with Sherwin-Williams and his two kids Kansas and Montana Jr. Has never taken alternative medicine of any kind, but thinks it will be an “easy sell.”",
    "reference_check": "Former employers all liked Montana. Montana was always quick to do whatever was asked of him, and almost always willing to stay late and help out extra whenever he was needed. Didn’t always take great initiative, so they had to stay on top of him a bit to make sure he kept busy, but he was more than capable of correctly performing any task that was asked of him."
  },
  {
    "repId": "rep65",
    "name": "Xavier Van Puten",
    "gender": "M",
    "education": "High School Education",
    "experience": "8 years telemarketing, Telemericaworks",
    "intelligence": 34,
    "myers_briggs": "ESTJ",
    "other_info": "Has won numerous awards for his model train collection",
    "interview": "Xavier Van Puten’s passion is certainly model trains. We talked about his collection for the first 5 minutes of the interview. During that conversation, it became clear that Xavier is a natural born salesperson, as he sold us on the fact that model trains were the future of entertainment. Van Puten was possibly our most unique interview yet. Something about him makes you want to know more.",
    "reference_check": "Xavier’s boss at Telemericaworks was not happy to learn that he was looking for another job. Xavier has been the #1 seller at Telemericaworks for 6 years straight, and he makes the company a lot of money. His co-workers all say that he is very weird, but undeniably the best employee in the company."
  },
  {
    "repId": "rep66",
    "name": "Laura Wakefield",
    "gender": "F",
    "education": "BS - Communications, Ole Miss University",
    "experience": "3 years in Customer Support at Kohl’s",
    "intelligence": 48,
    "myers_briggs": "ENTP",
    "other_info": "Volunteers at the Goodwill Collection Center once a month",
    "interview": "Quiet girl, very kind. Appropriately dressed, professional, nice smile. Did not have a whole lot to say about herself. Does not have any sales experience to speak of, but from working customer support at Kohl’s, Laura says she has become an excellent mediator and problem solver.",
    "reference_check": "References all check out. Personal references cite how charitable Laura is with her money. Lives below her means so she can afford to give money to her church and to homeless shelters. Previous employers all liked Laura. One boss at Kohl’s said that she had an uncanny ability to diffuse situations, and calm down angry customers."
  },
  {
    "repId": "rep67",
    "name": "Ralph Wilkins",
    "gender": "M",
    "education": "BA, English, Iowa State University",
    "experience": "5 years as a barista at Starbucks, 1 year in journalism with Iowa Tribune",
    "intelligence": 56,
    "myers_briggs": "INFJ",
    "other_info": "Volunteers at local library and as a local youth soccer official.",
    "interview": "Ralph came across as a true intellectual. Extensive vocabulary, yet refrained from using too many big words. Made a personal connection with everyone at the table. Has no sales experience and very limited real world business knowledge.",
    "reference_check": "Websites and publications that Ralph has written for say that he was always very timely with his submissions. The Editor-in-Chief at the Iowa Tribune seemed uneasy about offering any information about Ralph, except to say that he had indeed worked there in the past."
  },
  {
    "repId": "rep68",
    "name": "Serena Wilton",
    "gender": "F",
    "education": "High School",
    "experience": "13 years selling Mary Kay products in South Central, California",
    "intelligence": 68,
    "myers_briggs": "ESFJ",
    "other_info": "Founded the Compton College Charity her sophomore year in high school, remains an active leader to this day",
    "interview": "Very impressive person all around. Exceptional listener. Very well thought out and professionally written cover letter, printed on high quality paper.",
    "reference_check": "Amazing woman by all accounts. A top 10 Mary Kay salesperson in all of California. Spoke with several of her clients, all of which gave her glowing reviews. Fellow members of the Compton College Charity spoke in great detail about all the great work she has done for her community. Very highly regarded by all in her hometown."
  },
  {
    "repId": "rep69",
    "name": "Jasmine Winters",
    "gender": "F",
    "education": "BS HIstory, University of Florida",
    "experience": "7 years at Barnes & Noble",
    "intelligence": 36,
    "myers_briggs": "ISTJ",
    "other_info": "Cheerleader at University of Florida",
    "interview": "Striking woman with a distinct Florida accent. Recently moved up north to Ohio to be closer to her grandparents in their old age. Jasmine was incredibly friendly, easy to talk to, and had an engaging personality. A few interview questions stumped her, but she did a good job overall.",
    "reference_check": "Co-workers at Barnes & Noble all had nice things to say about Jasmine. A hard worker who showed up on time and did good work while at the store. She didn’t always make the best decisions, and sometimes had to ask a lot of questions before doing certain jobs (more so than other employees), but was still a valuable asset to the store."
  },
  {
    "repId": "rep70",
    "name": "Viktor Zukarov",
    "gender": "M",
    "education": "High School",
    "experience": "4 years as a cook for McDonald’s, 3 years as a server at Buffalo Wild Wings",
    "intelligence": 38,
    "myers_briggs": "INFJ",
    "other_info": "Fluent in Russian, Moved here from Russia at age 19",
    "interview": "Viktor is a very interesting person. He is a very tall and muscular individual that is into body-building. Says he works well with people of all ages. Teaches Russian as a second language to both kids and adults. Viktor thinks he will be good at sales because he has been successful selling Americans on the idea that they should learn Russian.",
    "reference_check": "Viktor’s references at McDonald’s and Buffalo Wild Wings talk about what an exceptionally hard worker he is. There were, however, some language barriers; in fact, McDonald's had to pull him off the drive-thru window because of too many misheard orders."
  }
];
