export default {
    "rep1": {
        "name": "Marvin Adams",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep1"
    },
    "rep2": {
        "name": "Karen Adams-Foster",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep2"
    },
    "rep3": {
        "name": "Quincey Alberta",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 1,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep3"
    },
    "rep4": {
        "name": "Henrietta Appleby",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep4"
    },
    "rep5": {
        "name": "Tyler Barnes",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 3,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep5"
    },
    "rep6": {
        "name": "Bartholomew Beasters",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 3,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep6"
    },
    "rep7": {
        "name": "Thomas Bexton III",
        "effort": 1,
        "sales": 1,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep7"
    },
    "rep8": {
        "name": "Rosanna Binghampton",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep8"
    },
    "rep9": {
        "name": "Rhonda Blalock",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 5,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep9"
    },
    "rep10": {
        "name": "Terry Brady",
        "effort": 3,
        "sales": 3,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 0,
        "id": "rep10"
    },
    "rep11": {
        "name": "Tori Braxton",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 1,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep11"
    },
    "rep12": {
        "name": "Thom Bromly",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep12"
    },
    "rep13": {
        "name": "Trinity Brown",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 4,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep13"
    },
    "rep14": {
        "name": "Kelly Byers",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep14"
    },
    "rep15": {
        "name": "Antonio Canseco",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 3,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep15"
    },
    "rep16": {
        "name": "Autumn Carrasco",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 3,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep16"
    },
    "rep17": {
        "name": "Devin Carter",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 3,
        "is_minority": 1,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep17"
    },
    "rep18": {
        "name": "David Catz",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 3,
        "is_minority": 0,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep18"
    },
    "rep19": {
        "name": "Rico Chaisson",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 4,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep19"
    },
    "rep20": {
        "name": "Diana Christopher",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep20"
    },
    "rep21": {
        "name": "Tim Cobb",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep21"
    },
    "rep22": {
        "name": "Bethany Cobblestone",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 4,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep22"
    },
    "rep23": {
        "name": "Yolanda Connors",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep23"
    },
    "rep24": {
        "name": "Morgan Cosfree",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep24"
    },
    "rep25": {
        "name": "Maria DeSilva",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep25"
    },
    "rep26": {
        "name": "Hannah Dixon",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 4,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep26"
    },
    "rep27": {
        "name": "Winston Druthers",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 4,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep27"
    },
    "rep28": {
        "name": "Hannibal Forrester",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 5,
        "incorrect_leadership_behavior": 1,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep28"
    },
    "rep29": {
        "name": "Eddie Fox",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep29"
    },
    "rep30": {
        "name": "Stevie Gonger",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep30"
    },
    "rep31": {
        "name": "Melanie Harrison",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 3,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep31"
    },
    "rep32": {
        "name": "Gregory Howe",
        "effort": 3,
        "sales": 3,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 0,
        "id": "rep32"
    },
    "rep33": {
        "name": "Brandon Howschwitz",
        "effort": 1,
        "sales": 1,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 3,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep33"
    },
    "rep34": {
        "name": "Wendy Hoyt",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep34"
    },
    "rep35": {
        "name": "Jennifer Huntley",
        "effort": 1,
        "sales": 1,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep35"
    },
    "rep36": {
        "name": "MaryJane Walters",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep36"
    },
    "rep37": {
        "name": "Marshall Jordie",
        "effort": 3,
        "sales": 3,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 0,
        "id": "rep37"
    },
    "rep38": {
        "name": "Tobias King",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 5,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep38"
    },
    "rep39": {
        "name": "Brian Lafevre",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 5,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep39"
    },
    "rep40": {
        "name": "Shaniqua Lexington",
        "effort": 1,
        "sales": 1,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 5,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep40"
    },
    "rep41": {
        "name": "Gina Mansfield",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep41"
    },
    "rep42": {
        "name": "Heather Marowick",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 4,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep42"
    },
    "rep43": {
        "name": "Roy McFreely",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 5,
        "incorrect_leadership_behavior": 4,
        "is_minority": 1,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep43"
    },
    "rep44": {
        "name": "Ishmael Mohammed",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 5,
        "is_minority": 1,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep44"
    },
    "rep45": {
        "name": "Nikki Monroe",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 3,
        "is_minority": 0,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep45"
    },
    "rep46": {
        "name": "Ricardo Montague",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 1,
        "is_minority": 1,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep46"
    },
    "rep47": {
        "name": "Rachel Ngatori",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep47"
    },
    "rep48": {
        "name": "Veronica Nightingale",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep48"
    },
    "rep49": {
        "name": "Carl Norfish",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep49"
    },
    "rep50": {
        "name": "Bristol O'Callahan Sr.",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 4,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep50"
    },
    "rep51": {
        "name": "Carmen O'Malley",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 3,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep51"
    },
    "rep52": {
        "name": "Terrance Olley",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 1,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep52"
    },
    "rep53": {
        "name": "Camille Parker",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep53"
    },
    "rep54": {
        "name": "Brady Ranger",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep54"
    },
    "rep55": {
        "name": "Hank Rolands",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep55"
    },
    "rep56": {
        "name": "Topanga Rusicallo",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep56"
    },
    "rep57": {
        "name": "Dakota Sandersmith",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 4,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep57"
    },
    "rep58": {
        "name": "Mike Schmeltz",
        "effort": 3,
        "sales": 3,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 0,
        "id": "rep58"
    },
    "rep59": {
        "name": "Roberta Shadows",
        "effort": 2,
        "sales": 1,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 3,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep59"
    },
    "rep60": {
        "name": "Easton Shelley",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 3,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep60"
    },
    "rep61": {
        "name": "Jasper Slawson",
        "effort": 1,
        "sales": 1,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 2,
        "id": "rep61"
    },
    "rep62": {
        "name": "Taylor Smith",
        "effort": 3,
        "sales": 2,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 1,
        "ind_hrs_2_plus": 2,
        "id": "rep62"
    },
    "rep63": {
        "name": "Fitzgerald St. James",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 5,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep63"
    },
    "rep64": {
        "name": "Montana Stone",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 5,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep64"
    },
    "rep65": {
        "name": "Xavier Van Puten",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 5,
        "incorrect_leadership_behavior": 4,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep65"
    },
    "rep66": {
        "name": "Laura Wakefield",
        "effort": 2,
        "sales": 2,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 1,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 2,
        "ind_hrs_2_plus": 3,
        "id": "rep66"
    },
    "rep67": {
        "name": "Ralph Wilkins",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 3,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep67"
    },
    "rep68": {
        "name": "Serena Wilton",
        "effort": 3,
        "sales": 3,
        "calls_per_qtr": 260,
        "correct_leadership_behavior": 4,
        "incorrect_leadership_behavior": 2,
        "is_minority": 1,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 0,
        "id": "rep68"
    },
    "rep69": {
        "name": "Jasmine Winters",
        "effort": 2,
        "sales": 3,
        "calls_per_qtr": 228,
        "correct_leadership_behavior": 5,
        "incorrect_leadership_behavior": 2,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep69"
    },
    "rep70": {
        "name": "Viktor Zukarov",
        "effort": 1,
        "sales": 2,
        "calls_per_qtr": 163,
        "correct_leadership_behavior": 2,
        "incorrect_leadership_behavior": 4,
        "is_minority": 0,
        "ind_hrs_0_1": 0,
        "ind_hrs_2_plus": 1,
        "id": "rep70"
    }
}