/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher/students'
import { Route as TeacherReportsRouteImport } from './routes/teacher/reports'
import { Route as TeacherDashboardRouteImport } from './routes/teacher/dashboard'
import { Route as StudentReportsRouteImport } from './routes/student/reports'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as AdminResultsRouteImport } from './routes/admin/results'
import { Route as AdminCompilationRouteImport } from './routes/admin/compilation'
import { Route as AdminAccessRouteImport } from './routes/admin/access'
import { Route as StudentDecisionsIndexRouteImport } from './routes/student/decisions/index'
import { Route as StudentRankingsSortRouteImport } from './routes/student/rankings/sort'
import { Route as StudentRankingsRefineRouteImport } from './routes/student/rankings/refine'
import { Route as StudentDecisionsLeadershipRouteImport } from './routes/student/decisions/leadership'
import { Route as StudentDecisionsHiringRouteImport } from './routes/student/decisions/hiring'

const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/teacher/students',
  path: '/teacher/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/teacher/reports',
  path: '/teacher/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentReportsRoute = StudentReportsRouteImport.update({
  id: '/student/reports',
  path: '/student/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/admin/results',
  path: '/admin/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompilationRoute = AdminCompilationRouteImport.update({
  id: '/admin/compilation',
  path: '/admin/compilation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/admin/access',
  path: '/admin/access',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDecisionsIndexRoute = StudentDecisionsIndexRouteImport.update({
  id: '/student/decisions/',
  path: '/student/decisions/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRankingsSortRoute = StudentRankingsSortRouteImport.update({
  id: '/student/rankings/sort',
  path: '/student/rankings/sort',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRankingsRefineRoute = StudentRankingsRefineRouteImport.update({
  id: '/student/rankings/refine',
  path: '/student/rankings/refine',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDecisionsLeadershipRoute =
  StudentDecisionsLeadershipRouteImport.update({
    id: '/student/decisions/leadership',
    path: '/student/decisions/leadership',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentDecisionsHiringRoute = StudentDecisionsHiringRouteImport.update({
  id: '/student/decisions/hiring',
  path: '/student/decisions/hiring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/compilation': typeof AdminCompilationRoute
  '/admin/results': typeof AdminResultsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/reports': typeof StudentReportsRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/student/decisions/hiring': typeof StudentDecisionsHiringRoute
  '/student/decisions/leadership': typeof StudentDecisionsLeadershipRoute
  '/student/rankings/refine': typeof StudentRankingsRefineRoute
  '/student/rankings/sort': typeof StudentRankingsSortRoute
  '/student/decisions/': typeof StudentDecisionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/compilation': typeof AdminCompilationRoute
  '/admin/results': typeof AdminResultsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/reports': typeof StudentReportsRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student': typeof StudentIndexRoute
  '/student/decisions/hiring': typeof StudentDecisionsHiringRoute
  '/student/decisions/leadership': typeof StudentDecisionsLeadershipRoute
  '/student/rankings/refine': typeof StudentRankingsRefineRoute
  '/student/rankings/sort': typeof StudentRankingsSortRoute
  '/student/decisions': typeof StudentDecisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/compilation': typeof AdminCompilationRoute
  '/admin/results': typeof AdminResultsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/reports': typeof StudentReportsRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/student/decisions/hiring': typeof StudentDecisionsHiringRoute
  '/student/decisions/leadership': typeof StudentDecisionsLeadershipRoute
  '/student/rankings/refine': typeof StudentRankingsRefineRoute
  '/student/rankings/sort': typeof StudentRankingsSortRoute
  '/student/decisions/': typeof StudentDecisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/request-access'
    | '/admin/access'
    | '/admin/compilation'
    | '/admin/results'
    | '/student/dashboard'
    | '/student/reports'
    | '/teacher/dashboard'
    | '/teacher/reports'
    | '/teacher/students'
    | '/student/'
    | '/student/decisions/hiring'
    | '/student/decisions/leadership'
    | '/student/rankings/refine'
    | '/student/rankings/sort'
    | '/student/decisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/request-access'
    | '/admin/access'
    | '/admin/compilation'
    | '/admin/results'
    | '/student/dashboard'
    | '/student/reports'
    | '/teacher/dashboard'
    | '/teacher/reports'
    | '/teacher/students'
    | '/student'
    | '/student/decisions/hiring'
    | '/student/decisions/leadership'
    | '/student/rankings/refine'
    | '/student/rankings/sort'
    | '/student/decisions'
  id:
    | '__root__'
    | '/login'
    | '/request-access'
    | '/admin/access'
    | '/admin/compilation'
    | '/admin/results'
    | '/student/dashboard'
    | '/student/reports'
    | '/teacher/dashboard'
    | '/teacher/reports'
    | '/teacher/students'
    | '/student/'
    | '/student/decisions/hiring'
    | '/student/decisions/leadership'
    | '/student/rankings/refine'
    | '/student/rankings/sort'
    | '/student/decisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  RequestAccessRoute: typeof RequestAccessRoute
  AdminAccessRoute: typeof AdminAccessRoute
  AdminCompilationRoute: typeof AdminCompilationRoute
  AdminResultsRoute: typeof AdminResultsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentReportsRoute: typeof StudentReportsRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentDecisionsHiringRoute: typeof StudentDecisionsHiringRoute
  StudentDecisionsLeadershipRoute: typeof StudentDecisionsLeadershipRoute
  StudentRankingsRefineRoute: typeof StudentRankingsRefineRoute
  StudentRankingsSortRoute: typeof StudentRankingsSortRoute
  StudentDecisionsIndexRoute: typeof StudentDecisionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/teacher/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/teacher/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/reports': {
      id: '/student/reports'
      path: '/student/reports'
      fullPath: '/student/reports'
      preLoaderRoute: typeof StudentReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/admin/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/compilation': {
      id: '/admin/compilation'
      path: '/admin/compilation'
      fullPath: '/admin/compilation'
      preLoaderRoute: typeof AdminCompilationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/decisions/': {
      id: '/student/decisions/'
      path: '/student/decisions'
      fullPath: '/student/decisions/'
      preLoaderRoute: typeof StudentDecisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/rankings/sort': {
      id: '/student/rankings/sort'
      path: '/student/rankings/sort'
      fullPath: '/student/rankings/sort'
      preLoaderRoute: typeof StudentRankingsSortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/rankings/refine': {
      id: '/student/rankings/refine'
      path: '/student/rankings/refine'
      fullPath: '/student/rankings/refine'
      preLoaderRoute: typeof StudentRankingsRefineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/decisions/leadership': {
      id: '/student/decisions/leadership'
      path: '/student/decisions/leadership'
      fullPath: '/student/decisions/leadership'
      preLoaderRoute: typeof StudentDecisionsLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/decisions/hiring': {
      id: '/student/decisions/hiring'
      path: '/student/decisions/hiring'
      fullPath: '/student/decisions/hiring'
      preLoaderRoute: typeof StudentDecisionsHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  RequestAccessRoute: RequestAccessRoute,
  AdminAccessRoute: AdminAccessRoute,
  AdminCompilationRoute: AdminCompilationRoute,
  AdminResultsRoute: AdminResultsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentReportsRoute: StudentReportsRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentDecisionsHiringRoute: StudentDecisionsHiringRoute,
  StudentDecisionsLeadershipRoute: StudentDecisionsLeadershipRoute,
  StudentRankingsRefineRoute: StudentRankingsRefineRoute,
  StudentRankingsSortRoute: StudentRankingsSortRoute,
  StudentDecisionsIndexRoute: StudentDecisionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
